[theme]

# Primary accent for interactive elements 
primaryColor = '#E694FF'

# Background color for the main content area  
backgroundColor =   linear-gradient(90deg, #4b6cb7 0%, #182848 100%) #'#02539D' 00172B

# Background color for sidebar and most interactive widgets 
secondaryBackgroundColor = '#00001c' 

# Color used for almost all text
textColor = '#FFFFFF'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"
